on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ main, devops ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy FS scan (container)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/project \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest fs /project \
              --format sarif \
              --output /project/trivy-results.sarif \
              --ignore-unfixed \
              --vuln-type library,config

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif